version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        - AWS_ACCESS_KEY_ID=your_aws_key
        - AWS_SECRET_ACCESS_KEY=your_aws_secret
        - AWS_DEFAULT_REGION=ap-south-1
        - JWT_SECRET=your_jwt_secret
    restart: unless-stopped
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge

volumes:
  node_modules: